name: Publish

on:
  push:
    branches:
    - master

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.88.1'

    - name: Build
      run: hugo -D

    - name: Deploy
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.1.0
      with:
        ftp_host: ${{ secrets.FTP_HOST }}
        ftp_username: ${{ secrets.FTP_USER }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
        local_source_dir: "public"
        dist_target_dir: "/"
        delete: "false"
